name: Major Assignment CI/CD Workflow
    
on: 
    push : 
        branches : main

jobs :
    test-suite :
        runs-on : ubuntu-latest

        steps :
            - name : Checkout
              uses : actions/checkout@v3
            
            - name : Setup Python
              uses : actions/setup-python@v4
              with :
                python-version : '3.9'

            - name : Installing Dependencies
              run : pip install -r requirements.txt

            - name : Runs pytest
              run : python -m pytest tests/test_train.py
    
    train_and_quantize :
        runs-on : ubuntu-latest
        needs : test-suite

        steps :
            - name : Checkout
              uses : actions/checkout@v3
            
            - name : Setting up Python
              uses : actions/setup-python@v4
              with :
                python-version : '3.9'

            - name : Installing Dependencies
              run : pip install -r requirements.txt

            - name : Training the model
              run : python src/train.py

            - name : Running the quantization
              run : python src/quantize.py

            - name : Uploading trained model as artifact
              uses : actions/upload-artifact@v4
              with :
                name : Trained Housing Model
                path : models/california_housing.joblib

            - name : Uploading unquantized model as artifact
              uses : actions/upload-artifact@v4
              with :
                name : Unquantized Model
                path : models/unquant_params.joblib

            
            - name : Uploading quantized model as artifact
              uses : actions/upload-artifact@v4
              with :
                name : Quantized Model
                path : models/quant_params.joblib
    
    build_and_test_container :
        runs-on : ubuntu-latest
        needs : train_and_quantize

        steps :
            - name : Checkout
              uses : actions/checkout@v3
            
            - name : Setting up Python
              uses : actions/setup-python@v4
              with :
                python-version : '3.9'

            - name : Installing Dependencies
              run : pip install -r requirements.txt

            - name : Training the model
              run : python src/train.py

            - name : Building Docker Image
              run : | 
                echo "Building Docker Image"
                docker build -t majorassignment .
                echo "Successfully built docker image"
                
            - name : Testing the Docker Container
              run : | 
                echo "Testing Docker Container"
                docker run majorassignment python predict.py
                echo "Container test completed"






    
